name: dartdap
version: 0.0.4
author: Warren Strange <warren.strange@gmail.com>
description: A dart LDAP v3 client library
homepage: https://github.com/wstrange/dartdap
environment:
  sdk: '>=1.7.10 <2.0.0'
dependencies:
  asn1lib: '>=0.3.3 <1.0.0'
  dart_config: 0.5.0
  logging: '>=0.9.0 <1.0.0'
dev_dependencies:
  logging_handlers: any
  unittest: any
