name: dartdap
version: 0.2.4
authors:
- Warren Strange <warren.strange@gmail.com>
- Chris Ridd <chrisridd@mac.com>
- Hoylen Sue <hoylen@hoylen.com>
- Matthew Butler <butler.matthew@gmail.com>
description: LDAP v3 client library for Dart
homepage: https://github.com/wstrange/dartdap
environment:
  sdk: '>=2.0.0-dev.69 <3.0.0'
dependencies:
  asn1lib: "^0.5.2"
  logging: "^0.11.2"
dev_dependencies:
  logging_handlers: "^0.8.0"
  dart_config: "^0.5.0"
  test: "1.2.0"
  yaml: "^2.1.14"
