name: dartdap
version: 0.0.1
author: Warren Strange <warren.strange@gmail.com>
description: A dart LDAP v3 client library
homepage: https://github.com/wstrange/dartdap
dependencies:
  asn1lib: 0.1.0
  dart_config: any
  logging: any
dev_dependencies:
  unittest: any
