name: dartdap
version: 0.0.11
authors:
- Warren Strange <warren.strange@gmail.com>
- Chris Ridd <chrisridd@mac.com>
- Hoylen Sue <hoylen@hoylen.com>
description: LDAP v3 client library for Dart
homepage: https://github.com/wstrange/dartdap
environment:
  sdk: '>=1.9.1 <2.0.0'
dependencies:
  asn1lib: "^0.4.0"
  dart_config: "^0.5.0"
  logging: "^0.11.2"
dev_dependencies:
  logging_handlers: "^0.8.0"
  test: "^0.12.10"
