name: dartdap
version: 0.0.2
author: Warren Strange <warren.strange@gmail.com>
description: A dart LDAP v3 client library
homepage: https://github.com/wstrange/dartdap
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  asn1lib: '>=0.1.1'
  dart_config: 0.5.0
  logging: 0.9.0
dev_dependencies:
  quiver: 0.13.0
  unittest: any
